local M = {}

-- editorapi is used to determine state and integration for the editor

function M.warn(msg)
    vim.notify(msg, vim.log.levels.WARN)
end

---Jump to next '_', uppercase letter, or word boundary in the current buffer
---@param action string | nil d for delete and c for change
---@param flag   string | nil flag for the action, "f" or "t" (find or til)
function M.jump_half_word(action, flag)
    -- Save current position
    local row, col = unpack(vim.api.nvim_win_get_cursor(0))
    -- Search pattern: _ or [A-Z] or word boundary (\<)
    local pattern = [[\(_\w\|\u\|\<\)]]
    -- Search forward, no [W]rap and go to [e]nd
    local found = vim.fn.search(pattern, 'We')
    if found == 0 then
        -- Not found, restore cursor
        vim.api.nvim_win_set_cursor(0, {row, col})
        return
    end
    if action == nil then
        return
    end
    if action == 'd' or action == 'c' then
        local new_row, new_col = unpack(vim.api.nvim_win_get_cursor(0))
        vim.api.nvim_win_set_cursor(0, {row, col})
        -- enter visual mode
        vim.cmd('normal! v')
        if flag == 't' then
            vim.api.nvim_win_set_cursor(0, {new_row, new_col - 1})
        else
            vim.api.nvim_win_set_cursor(0, {new_row, new_col})
        end
        vim.cmd('normal! d')
        if action == 'c' then
            vim.cmd('startinsert')
        end
        return
    end
end

M.tabt = {
    EDIT = 0,     -- MainEdit: NvimTree and 1 or 2 opened file buffers
    AIDIFF = 1,   -- AiDiff:   Viewing diff generated by AI in a different tabpage
    DIFF = 2,     -- MainDiff: Viewing diff explorer and 2 or 3 way diff
    TERM = 3,     -- Accessing floating terminal in any view
    SEARCH = 4    -- Telescope
}

M.buft = {
    TREE = 0,     -- EDIT, buffer for NvimTree
    NOTIF = 1,    -- EDIT, buffer for notification window
    FILE = 2,     -- EDIT, buffer for normal file
    FILETERM = 3, -- EDIT, buffer for terminal opened next to file
    FLOATERM = 4, -- TERM, buffer for floating terminal
    AIFILE = 5,   -- AIDIFF, the buffer for normal file (the one AI is proposing to change)
    AIDIFF = 6,   -- AIDIFF, the buffer for proposed change
    DIFFTREE = 7, -- DIFF, the file explorer buffer
    DIFFFILE = 8, -- DIFF, the file (not sure how to detect "old" vs "new", should be a way)
    SEARCH = 9    -- SEARCH
}

---Get the screen type for the buffer
---@param bufnr integer | nil the buffer number, 0 or nil for current
---@param tabpage integer | nil the tabpage number for tabpage based inferrence, default to current tabpage
---@return integer, integer  tabtyp and buftyp
function M.viewtyp(bufnr, tabpage)
    local filetype
    local buftype
    if bufnr ~= nil then
        filetype = vim.bo[bufnr].filetype
        buftype = vim.bo[bufnr].buftype
    else
        filetype = vim.bo.filetype
        buftype = vim.bo.buftype
    end
    if filetype == "NvimTree" then
        return M.tabt.EDIT, M.buft.TREE
    end
    if filetype == "codediff-explorer" then
        return M.tabt.DIFF, M.buft.DIFFTREE
    end
    if filetype == "claude-notify" then
        return M.tabt.EDIT, M.buft.NOTIF
    end
    if filetype == "floaterm" then
        return M.tabt.TERM, M.buft.FLOATERM
    end
    if buftype == "terminal" then
        -- right now only non-float terminal is file term
        return M.tabt.EDIT, M.buft.FILETERM
    end
    if string.find(filetype, "Telescope") then
        return M.tabt.SEARCH, M.buft.SEARCH
    end
    if vim.api.nvim_buf_get_name(bufnr or 0):match("claude[/\\]proposed$") ~= nil
    then
        return M.tabt.AIDIFF, M.buft.AIDIFF
    end
    -- actually check visibility of all windows on the current tabpage
    for _, winid in ipairs(vim.api.nvim_tabpage_list_wins(tabpage or 0)) do
        local b = vim.api.nvim_win_get_buf(winid)
        local b_name = vim.api.nvim_buf_get_name(b)
        if b_name:match("claude[/\\]proposed$") ~= nil then
            -- self is not AIDIFF, but AIDIFF tab open,
            -- self must be AIFILE
            return M.tabt.AIDIFF, M.buft.AIFILE
        end
        local b_filetype = vim.bo[b].filetype
        if b_filetype == "codediff-explorer" then
            -- self is not codediff-explorer, but is open
            -- in same tab, must be diff file
            return M.tabt.DIFF, M.buft.DIFFFILE
        end
    end
    -- must be normal file
    return M.tabt.EDIT, M.buft.FILE
end

---Get the buftyp for the buffer in the current tabpage
---@param bufnr integer | nil the buffer number, 0 or nil for current
---@return integer  buftyp
function M.buftyp(bufnr)
    local _, b = M.viewtyp(bufnr)
    return b
end

---Get the tabtyp for the buffer in the current tabpage
---@param bufnr integer | nil the buffer number, 0 or nil for current
---@return integer  tabtyp
function M.tabtyp(bufnr)
    local t, _ = M.viewtyp(bufnr)
    return t
end

---Get a mapping between tabtyp and tabpage id
function M.query_tabpages()
    local tabpages = vim.api.nvim_list_tabpages()
    local out = {}
    for _, tabpage in ipairs(tabpages) do
        for _, winid in ipairs(vim.api.nvim_tabpage_list_wins(tabpage)) do
            local bufnr = vim.api.nvim_win_get_buf(winid)
            local tt, _ = M.viewtyp(bufnr, tabpage)
            if tt == M.tabt.EDIT or tt == M.tabt.AIDIFF or tt == M.tabt.DIFF then
                out[tt] = tabpage
                break
            end
        end
    end
    return out
end

---Switch to tab based on type, execute the callback if succeeded
---return true if switch successful
function M.switch_tab_then(tab_type, cb)
    local tabpages = M.query_tabpages()
    local tabpage = tabpages[tab_type]
    if tabpage == nil then
        M.warn("cannot find requested tabpage")
        return false
    end
    local current = vim.api.nvim_get_current_tabpage()
    if current == tabpage then
        if cb then cb() end
    else
        vim.api.nvim_set_current_tabpage(tabpage)
        if cb then vim.defer_fn(cb, 30) end
    end
    return true
end

---Swap editing files left and right
function M.swap_editing_files()
    local tt = M.tabtyp()
    if tt ~= M.tabt.EDIT then
        M.warn("not in edit view")
        return
    end
    vim.cmd.NvimTreeClose()
    vim.api.nvim_input("<C-w>r")
    vim.defer_fn(function ()
        vim.cmd.NvimTreeOpen()
        vim.api.nvim_input("<C-w>l")
    end, 1)
end

---Jump to dianostic
---@param count integer      -1 for previous, 1 for next
---@param error_only boolean filter to only errors
function M.jump_diagnostic(count, error_only)
    if error_only then
        vim.diagnostic.jump({ count = count, severity = vim.diagnostic.severity.ERROR })
    else
        vim.diagnostic.jump({ count = count })
    end
    -- show diagnostic window
    vim.defer_fn(function()
        vim.diagnostic.open_float({ scope = 'cursor' })
    end, 50)
end

---Show a new floaterm if already in floaterm
function M.new_floaterm()
    local tt = M.tabtyp()
    if tt == M.tabt.TERM then
        -- already in floaterm, make a new one
        vim.cmd.FloatermNew()
        return
    end
    -- switch to editview then new floaterm
    M.switch_to_editview_then(vim.cmd.FloatermNew)
end

function M.cycle_floaterm()
    local tt = M.tabtyp()
    if tt == M.tabt.TERM then
        vim.cmd.FloatermNext()
    end
end

function M.close_fileterm()
    if M.buftyp() == M.buft.FILETERM then
        vim.cmd("close")-- close the file terminal
    end
end

function M.fileterm_ctrl_w()
    vim.cmd("stopinsert") -- to normal mode
    if M.buftyp() == M.buft.FILETERM then
        -- also execute another C-w to be ready to switch focus
        vim.api.nvim_input("<C-w>")
    end
end

--- (Only available in EDIT tab) Focus the window that's on (close the other), then call CB
function M.editview_focus_then(cb)
    local tt, bt = M.viewtyp()
    if tt ~= M.tabt.EDIT or bt == M.buft.FILETERM or bt == M.buft.TREE then
        M.warn("operation not supported on current window")
        return
    end
    local window = vim.api.nvim_get_current_win();
    for _, winid in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
        if winid ~= window then
            local bufnr = vim.api.nvim_win_get_buf(winid)
            if M.buftyp(bufnr) ~= M.buft.NOTIF then
                vim.api.nvim_win_hide(winid)
            end
        end
    end
    vim.cmd.NvimTreeOpen()
    vim.api.nvim_input("<C-w>l")
    vim.defer_fn(cb, 30)
end

function M.editview_duplicate(right)
    M.editview_focus_then(function()
        if right then
            vim.api.nvim_input('<C-w>v<C-W>l')
        else
            vim.api.nvim_input('<C-w>v')
        end
    end)
end

function M.switch_to_editview_then(cb)
    M.switch_tab_then(M.tabt.EDIT, function()
        local bt = M.buftyp()
        if bt == M.buft.FILETERM then
            -- switch focus to other view
            vim.cmd("stopinsert")
            vim.api.nvim_input("<C-w>h")
            if cb then vim.defer_fn(cb, 30) end
            return
        end
        if bt == M.buft.FLOATERM then
            vim.cmd.FloatermToggle()
            if cb then vim.defer_fn(cb, 30) end
            return
        end
        if cb then cb() end
    end)
end

function M.open_file_finder()
    M.switch_to_editview_then(function()
        local builtin = require('telescope.builtin')
        builtin.find_files {
            attach_mappings = function(bufnr, map)
                map("i", "<C-l>", function()
                    local actions = require "telescope.actions"
                    actions.close(bufnr)
                    vim.defer_fn(function()
                        local action_state = require "telescope.actions.state"
                        local selection = action_state.get_selected_entry()
                        vim.cmd("ClaudeCodeAdd " .. selection[1])
                        -- keep focus inside fileterm
                        vim.api.nvim_input("<C-w>l")
                    end, 100)
                end)
                -- needs to return true to map default_mappings
                return true
            end
        }
    end)
end

function M.open_last_finder()
    M.switch_to_editview_then(function() vim.cmd("Telescope resume") end)
end

function M.open_live_grep_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").live_grep() end)
end

function M.open_buffer_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").buffers() end)
end

function M.open_definition_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").lsp_definitions() end)
end

function M.open_reference_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").lsp_references() end)
end

function M.open_implementation_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").lsp_implementations() end)
end

---View diagnostics of current buffer
function M.open_diagnostic_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").diagnostics({ bufnr = 0 }) end)
end

function M.open_symbol_finder()
    M.switch_to_editview_then(function() require("telescope.builtin").treesitter() end)
end

---Switch to EDIT and open AI Coder
function M.open_aicoder()
    local do_open_aicoder = function()
        M.editview_focus_then(function()
            vim.cmd.ClaudeCode()
        end)
    end

    M.switch_tab_then(M.tabt.EDIT, function()
        local bt = M.buftyp()
        if bt == M.buft.FILETERM then
            -- already in
            vim.cmd("startinsert")
            return
        end
        if bt == M.buft.FLOATERM then
            vim.cmd.FloatermToggle()
            vim.defer_fn(do_open_aicoder, 30)
            return
        end
        do_open_aicoder()
    end)
end

---Close AI Coder UI when in EDIT view
---Or close AI Coder Diff when in AIDiff view
function M.close_aicoder()
    local tt = M.tabtyp()
    if tt == M.tabt.EDIT then
        for _, winid in ipairs(vim.api.nvim_list_wins()) do
            local bufnr = vim.api.nvim_win_get_buf(winid)
            if M.buftyp(bufnr) == M.buft.FILETERM then
                vim.api.nvim_win_hide(winid)
            end
        end
        vim.cmd.ClaudeCodeNotificationDismiss()
        return
    end
    if tt == M.tabt.AIDIFF then
        vim.cmd.CodeDiff()
        vim.defer_fn(function()
            M.switch_to_editview_then(nil)
        end, 30)
        return
    end
end

---If not looking at AIDiff, open it
---Otherwise accept it
function M.open_or_accept_aidiff()
    local tt = M.tabtyp()
    if tt == M.tabt.AIDIFF then
        -- already looking at diff, accept it
        -- make sure no unsaved modifications in all opened windows
        for _, winid in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
            local bufnr = vim.api.nvim_win_get_buf(winid)
            local buft = M.buftyp(bufnr)
            if buft == M.buft.AIDIFF or buft == M.buft.AIFILE then
                if vim.bo[bufnr].modified then
                    M.warn("diff is unsaved, must save before accepting")
                    return
                end
            end
        end
        local curr_tabpage = vim.api.nvim_get_current_tabpage()
        vim.cmd.ClaudeCodeDiffAccept()
        M.switch_to_editview_then(function()
            -- close the aidiff
            vim.cmd(vim.api.nvim_tabpage_get_number(curr_tabpage) .. "tabclose")
            -- close any dangling aidiff buffers if needed
            for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
                if M.buftyp(bufnr) == M.buft.AIDIFF then
                    vim.api.nvim_buf_delete(bufnr, {force=false})
                end
            end
            M.warn("accepted aidiff")
        end)
    end
    local tabpages = M.query_tabpages()
    local tabpage_aidiff = tabpages[M.tabt.AIDIFF]
    if tabpage_aidiff == nil then
        -- open new code diff
        vim.cmd.ClaudeCodeOpenCodeDiff()
        return
    end
    M.switch_tab_then(M.tabt.AIDIFF, nil)
end

function M.deny_aidiff()
    -- note we allow denying without the diff open
    -- say we forgot some instruction and want to deny the output
    -- without checking
    local curr_tabpage = vim.api.nvim_get_current_tabpage()
    local is_in_aidiff = M.tabtyp() == M.tabt.AIDIFF
    M.switch_to_editview_then(function()
        vim.cmd.ClaudeCodeDiffDeny()
        vim.cmd(vim.api.nvim_tabpage_get_number(curr_tabpage) .. "tabclose")
        -- force close the diff buffers
        for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
            if M.buftyp(bufnr) == M.buft.AIDIFF then
                vim.api.nvim_buf_delete(bufnr, {force=true})
            end
        end
        if is_in_aidiff then
            -- probably want to tell AI what to do differently
            vim.cmd.ClaudeCodeFocus()
        end
        M.warn("denied aidiff")
    end)
end

---Send context to AI Coder
---@param visual boolean if in visual mode
function M.send_to_aicoder(visual)
    local tt, bt = M.viewtyp()
    if tt ~= M.tabt.EDIT then
        return
    end
    if bt == M.buft.TREE then
        if visual then return end
        -- send file in tree
        vim.cmd.ClaudeCodeTreeAdd()
        vim.cmd.ClaudeCodeFocus()
        return
    end
    if bt ~= M.buft.FILE then
        return
    end
    M.editview_focus_then(function()
        if visual then
            vim.api.nvim_input("gv<cmd>ClaudeCodeSend<cr>")
        else
            vim.cmd("ClaudeCodeAdd %")
        end
        -- keep focus inside fileterm
        vim.defer_fn(function()
            if M.buftyp() ~= M.buft.FILETERM then
                vim.cmd("stopinsert")
                vim.api.nvim_input("<C-w>l")
                vim.cmd("startinsert")
            end
        end, 100)
    end)
end

local git_diff_type = ""

---
function M.open_git_diff(diff_type)
    local tabpages = M.query_tabpages()
    local tabpage_diff = tabpages[M.tabt.DIFF]
    local do_open = function()
        git_diff_type = diff_type
        if diff_type == "status" then
            vim.cmd.CodeDiff()
            return
        end
        -- otherwise it could be:
        -- A..B: diff from commit A to commit B
        -- A: (just the commit/branch name)
        if diff_type:find("%.%.") then
            local a, b = diff_type:match("(.+)%.%.(.+)")
            if a and b then
                vim.cmd("CodeDiff " .. a .. " " .. b)
            end
        else
            vim.cmd("CodeDiff " .. diff_type)
        end

    end
    if tabpage_diff ~= nil then
        -- if a different diff is opened, close it
        if git_diff_type ~= diff_type then
            vim.api.nvim_command(vim.api.nvim_tabpage_get_number(tabpage_diff).. "tabclose")
            M.switch_to_editview_then(do_open)
        else
            -- otherwise just open that diff
            M.switch_tab_then(M.tabt.DIFF, nil)
        end
        return
    end
    -- no diff opened, just open new one
    M.switch_to_editview_then(do_open)
end

return M
